version: 2
jobs:
  build:
    docker:
      - image: ercoppa/fuzzolic-ci-runner
    steps:
      - run:
          name: Avoid hosts unknown for github
          command: | 
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config 
      - run:
          name: Fetching repo
          command: |
            git clone git@github.com:season-lab/fuzzolic.git
            sed -i -e 's#https://github.com/season-lab#git@github.com:season-lab#g' fuzzolic/.git/config
            cd fuzzolic && git submodule sync && git submodule update --init
            ls
