version: 2
jobs:
  build:
    docker:
      - image: ercoppa/fuzzolic-ci-runner
    steps:
      - run:
          name: Fetching repo
          command: |
            git clone https://github.com/season-lab/fuzzolic.git
            cd fuzzolic && git submodule sync && git submodule update --init
            ls
