version: 2
jobs:
  build:
    docker:
      - image: ercoppa/fuzzolic-ci-runner
    steps:
      - run:
          name: Avoid hosts unknown for github
          command: | 
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config 
      - run:
          name: Fetching repo
          command: |
            git clone git@github.com:season-lab/fuzzolic.git
            sed -i -e 's#https://github.com/season-lab#git@github.com:season-lab#g' fuzzolic/.git/config
            sed -i -e 's#https://github.com/season-lab#git@github.com:season-lab#g' fuzzolic/.gitmodules
            cd fuzzolic && git submodule sync && git submodule update --init
      - restore_cache:
          key: fuzzolic-tracer-{{ checksum "fuzzolic/.git/modules/tracer/HEAD" }}
      - run: 
          name: Building tracer
          working_directory: fuzzolic/tracer
          command: |
            [[ -f x86_64-linux-user/qemu-x86_64 ]] || ./configure --prefix=`pwd`/../build --target-list=x86_64-linux-user
            [[ -f x86_64-linux-user/qemu-x86_64 ]] || make -j `nproc`
      - save_cache:
          key: fuzzolic-tracer-{{ checksum "fuzzolic/.git/modules/tracer/HEAD" }}
          paths:
            - fuzzolic/tracer
      - run: 
          name: Fetching fuzzy-sat
          working_directory: fuzzolic/solver
          command: |
            [[ -d fuzzolic-z3 ]] || (cd fuzzy-sat && sed -i -e 's#https://github.com/season-lab#git@github.com:season-lab#g' fuzzy-sat/.gitmodules && git submodule sync && git submodule update --init)
      - restore_cache:
          key: fuzzolic-z3-{{ checksum "fuzzolic/.git/modules/solver/fuzzy-sat/modules/fuzzolic-z3/refs/heads/fuzzolic" }}
      - run: 
          name: Building Z3
          working_directory: fuzzolic/solver/fuzzy-sat
          command: |
            [[ -d fuzzolic-z3/build/dist ]] || (cd fuzzolic-z3 && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=`pwd`/dist && make -j `nproc` && make install && cd ../..)
            # caching Z3 build when localbuild
            if [[ ${CIRCLE_SHELL_ENV} =~ "localbuild" ]]; then
              if [[ -d fuzzolic-z3/build/dist ]]; then
                mkdir -p /repo/solver/fuzzy-sat/fuzzolic-z3/build/
                cp -a fuzzolic-z3/build/dist /repo/solver/fuzzy-sat/fuzzolic-z3/build/
              fi
            fi
      - save_cache:
          key: fuzzolic-z3-{{ checksum "fuzzolic/.git/modules/solver/fuzzy-sat/modules/fuzzolic-z3/refs/heads/fuzzolic" }}
          paths:
            - fuzzolic/solver/fuzzy-sat/fuzzolic-z3
