version: 2
jobs:
  build:
    docker:
      - image: ercoppa/fuzzolic-ci-runner
    steps:
      - run:
          name: Avoid hosts unknown for github
          command: | 
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config 
      - run:
          name: Fetching repo
          command: |
            git clone git@github.com:season-lab/fuzzolic.git
            sed -i -e 's#https://github.com/season-lab#git@github.com:season-lab#g' fuzzolic/.git/config
            sed -i -e 's#https://github.com/season-lab#git@github.com:season-lab#g' fuzzolic/.gitmodules
            cd fuzzolic && git submodule sync && git submodule update --init
      - restore_cache:
          key: fuzzolic-tracer-{{ checksum "fuzzolic/.git/modules/tracer/HEAD" }}
      - run: 
          name: Building tracer
          working_directory: fuzzolic/tracer
          command: |
            [[ -f x86_64-linux-user/qemu-x86_64 ]] || ./configure --prefix=`pwd`/../build --target-list=x86_64-linux-user
            [[ -f x86_64-linux-user/qemu-x86_64 ]] || make -j `nproc`
      - save_cache:
          key: fuzzolic-tracer-{{ checksum "fuzzolic/.git/modules/tracer/HEAD" }}
          paths:
            - fuzzolic/tracer
